# Generated by Django 4.2.2 on 2023-06-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('message', models.TextField(max_length=256, verbose_name='Отзыв')),
                ('date', models.CharField(blank=True, max_length=11, verbose_name='Дата отправки')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('phone', models.CharField(max_length=64, verbose_name='Номер телефона')),
                ('date', models.DateTimeField(blank=True, max_length=11, verbose_name='Дата записи')),
                ('message', models.TextField(max_length=256, verbose_name='Сообщение')),
            ],
        ),
    ]
